/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletsIndexRouteImport } from './routes/wallets.index'
import { Route as WalletsWalletIdRouteImport } from './routes/wallets.$walletId'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsIndexRoute = WalletsIndexRouteImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsWalletIdRoute = WalletsWalletIdRouteImport.update({
  id: '/wallets/$walletId',
  path: '/wallets/$walletId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/wallets/': typeof WalletsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/wallets': typeof WalletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/budget': typeof BudgetRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/wallets/': typeof WalletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/budget'
    | '/settings'
    | '/transactions'
    | '/wallets/$walletId'
    | '/wallets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/budget'
    | '/settings'
    | '/transactions'
    | '/wallets/$walletId'
    | '/wallets'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/budget'
    | '/settings'
    | '/transactions'
    | '/wallets/$walletId'
    | '/wallets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BudgetRoute: typeof BudgetRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  WalletsWalletIdRoute: typeof WalletsWalletIdRoute
  WalletsIndexRoute: typeof WalletsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets/': {
      id: '/wallets/'
      path: '/wallets'
      fullPath: '/wallets/'
      preLoaderRoute: typeof WalletsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets/$walletId': {
      id: '/wallets/$walletId'
      path: '/wallets/$walletId'
      fullPath: '/wallets/$walletId'
      preLoaderRoute: typeof WalletsWalletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BudgetRoute: BudgetRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  WalletsWalletIdRoute: WalletsWalletIdRoute,
  WalletsIndexRoute: WalletsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
